### ISSUE TITLE
Moving jar results in Spring Boot 404

### ISSUE THREAD

**Issue by b-long** [RedFroggy/angular-spring-dynamic-form#6]
I'm unsure if this is the result of user error, but I think it's best to report and collaborate to triage.
 
### Expected behavior
The application is available by navigating to http://localhost:8080/

### Actual behavior
The following 404 page is displayed.
![screenshot from 2017-01-23 22-43-52](https://cloud.githubusercontent.com/assets/66993/22233642/a537f09e-e1bf-11e6-8854-1c8f4b82a584.png)

### Steps to reproduce
1. Build the project in the conventional fashion: `mvn clean package`
2. Copy the generated jar to a new directory: `cp target/spring-angular-dynamic-form-1.0-SNAPSHOT.jar /tmp/` 
3. Run the copied jar: `cd /tmp/ && java -jar spring-angular-dynamic-form-1.0-SNAPSHOT.jar` 
4. Open your browser to http://localhost:8080 and observe the 404 page.

### Note
The 404 isn't displayed and the application functions normally if the jar is executed in the build directory (e.g. in the git repo root, invoking `java -jar target/spring-angular-dynamic-form-1.0-SNAPSHOT.jar` )

**Comment by b-long** [comment]
It seems that the Spring directs the user against `src/main/webapp/` if the project is to be packaged as a jar.  Quoting the [official documentation](http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-developing-web-applications.html#boot-features-spring-mvc-static-content) : 

> Do not use the `src/main/webapp` directory if your application will be packaged as a jar. Although this directory is a common standard, it will only work with war packaging and it will be silently ignored by most build tools if you generate a jar.

This looks to be a pain point for other developers : 
* http://stackoverflow.com/questions/28725635/spring-boot-configure-it-to-find-the-webapp-folder
* http://stackoverflow.com/questions/35968479/spring-boot-cannot-find-index-html-under-webapp-folder

Per the documentation, it seems Spring Boot users are expected to place front-end assets in one of the following:
 
> /public (or /static or /resources or /META-INF/resources)

If if I'm understanding correctly, the first being `src/main/resources/public` .

What are your thoughts on this issue? 

cc/  @RedFroggy, @michaeldesigaud

**Comment by michaeldesigaud** [comment]
I fixed the issue by moving static resources to the src/main/resources/static folder as you mentionned and it works perfectly !

Thanks a lot for your feedback and the very detailed issue !
